/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.farmacia.gui;

import javax.swing.JOptionPane;

/**
 *
 * @author Evanilson
 */
public class TelaSistema extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public TelaSistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jMenuBarSistema = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuCliente = new javax.swing.JMenu();
        jMenuItemCadCliente = new javax.swing.JMenuItem();
        jMenuAlterar = new javax.swing.JMenu();
        jMenuItemAltCliente = new javax.swing.JMenuItem();
        jMenuRemover = new javax.swing.JMenu();
        jMenuItemRemCliente = new javax.swing.JMenuItem();
        jMenuConsultar = new javax.swing.JMenu();
        jMenuItemConCliente = new javax.swing.JMenuItem();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Principal");
        setResizable(false);

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        jMenuArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/farmacia/resources/ico/house.png"))); // NOI18N
        jMenuArquivo.setText("Arquivo");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemSair);

        jMenuBarSistema.add(jMenuArquivo);

        jMenuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/farmacia/resources/ico/add.png"))); // NOI18N
        jMenuCliente.setText("Cadastrar");

        jMenuItemCadCliente.setText("Cliente");
        jMenuItemCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadClienteActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuItemCadCliente);

        jMenuBarSistema.add(jMenuCliente);

        jMenuAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/farmacia/resources/ico/page_edit.png"))); // NOI18N
        jMenuAlterar.setText("Alterar");

        jMenuItemAltCliente.setText("Cliente");
        jMenuAlterar.add(jMenuItemAltCliente);

        jMenuBarSistema.add(jMenuAlterar);

        jMenuRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/farmacia/resources/ico/delete.png"))); // NOI18N
        jMenuRemover.setText("Remover");

        jMenuItemRemCliente.setText("Cliente");
        jMenuRemover.add(jMenuItemRemCliente);

        jMenuBarSistema.add(jMenuRemover);

        jMenuConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/farmacia/resources/ico/magnifier.png"))); // NOI18N
        jMenuConsultar.setText("Consultar");

        jMenuItemConCliente.setText("Cliente");
        jMenuConsultar.add(jMenuItemConCliente);

        jMenuBarSistema.add(jMenuConsultar);

        jMenuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/farmacia/resources/ico/help.png"))); // NOI18N
        jMenuAjuda.setText("Ajuda");

        jMenuSobre.setText("Sobre");
        jMenuAjuda.add(jMenuSobre);

        jMenuBarSistema.add(jMenuAjuda);

        setJMenuBar(jMenuBarSistema);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(null, "Deseja sair do sistema?", "Sair - Sistema Farmácia v1.0", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadClienteActionPerformed
        // TODO add your handling code here:
        TelaCadastroCliente telaCadCliente = new TelaCadastroCliente();
        telaCadCliente.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenu jMenuAlterar;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBarSistema;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenu jMenuConsultar;
    private javax.swing.JMenuItem jMenuItemAltCliente;
    private javax.swing.JMenuItem jMenuItemCadCliente;
    private javax.swing.JMenuItem jMenuItemConCliente;
    private javax.swing.JMenuItem jMenuItemRemCliente;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuRemover;
    private javax.swing.JMenuItem jMenuSobre;
    private javax.swing.JPanel jPanelPrincipal;
    // End of variables declaration//GEN-END:variables
}
