/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import br.com.farmacia.beans.Funcionario;

import br.com.farmacia.dao.FuncionarioDAO;
import br.com.farmacia.util.Util;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Evanilson
 */
public class TelaAlterarFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultaFuncionario
     */
    public TelaAlterarFuncionario() {
        initComponents();
        jLabelCodigoFuncionario.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBoxCodigoCpf = new javax.swing.JComboBox();
        jTextFieldCodigoCpfFuncionario = new javax.swing.JTextField();
        jLabelNomeFuncionario = new javax.swing.JLabel();
        jTextFieldNomeFuncionario = new javax.swing.JTextField();
        jLabelRgFuncionario = new javax.swing.JLabel();
        jTextFieldRgFuncionario = new javax.swing.JTextField();
        jLabelCpfFuncionario = new javax.swing.JLabel();
        jTextFieldCpfFuncionario = new javax.swing.JTextField();
        jLabelDataNascFuncionario = new javax.swing.JLabel();
        jTextFieldDataNascFuncionario = new javax.swing.JTextField();
        jLabelEndereçoFuncionario = new javax.swing.JLabel();
        jTextFieldEnderecoFuncionario = new javax.swing.JTextField();
        jLabelTelefoneFuncionario = new javax.swing.JLabel();
        jTextFieldTelefoneFuncionario = new javax.swing.JTextField();
        jLabelFuncaoFuncionario = new javax.swing.JLabel();
        jTextFieldFuncaoFuncionario = new javax.swing.JTextField();
        jLabelSalarioFuncionario = new javax.swing.JLabel();
        jTextFieldSalarioFuncionario = new javax.swing.JTextField();
        jButtonCancelarFuncionario = new javax.swing.JButton();
        jButtonConsultarFuncionario = new javax.swing.JButton();
        jLabelCodigoFuncionario = new javax.swing.JLabel();
        jButtonAlterarFuncionario = new javax.swing.JButton();
        jLabelAlterardeFuncionario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBoxCodigoCpf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Código", "CPF" }));
        jComboBoxCodigoCpf.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCodigoCpfItemStateChanged(evt);
            }
        });

        jLabelNomeFuncionario.setText("Nome:");

        jLabelRgFuncionario.setText("RG:");

        jLabelCpfFuncionario.setText("CPF:");

        jLabelDataNascFuncionario.setText("Data de Nascimento:");

        jLabelEndereçoFuncionario.setText("Endereço:");

        jLabelTelefoneFuncionario.setText("Talefone:");

        jLabelFuncaoFuncionario.setText("Função:");

        jTextFieldFuncaoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFuncaoFuncionarioActionPerformed(evt);
            }
        });

        jLabelSalarioFuncionario.setText("Salario:");

        jButtonCancelarFuncionario.setText("Cancelar");

        jButtonConsultarFuncionario.setText("Consultar");
        jButtonConsultarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarFuncionarioActionPerformed(evt);
            }
        });

        jButtonAlterarFuncionario.setText("Atualizar");
        jButtonAlterarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxCodigoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDataNascFuncionario)
                    .addComponent(jLabelCpfFuncionario)
                    .addComponent(jLabelRgFuncionario)
                    .addComponent(jLabelNomeFuncionario)
                    .addComponent(jLabelEndereçoFuncionario)
                    .addComponent(jLabelTelefoneFuncionario)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelFuncaoFuncionario)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCodigoFuncionario)
                            .addComponent(jLabelSalarioFuncionario))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldNomeFuncionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(jTextFieldEnderecoFuncionario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldFuncaoFuncionario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCodigoCpfFuncionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRgFuncionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCpfFuncionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDataNascFuncionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTelefoneFuncionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSalarioFuncionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jButtonConsultarFuncionario)
                .addGap(89, 89, 89))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelarFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAlterarFuncionario)
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCodigoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCodigoCpfFuncionario)
                    .addComponent(jButtonConsultarFuncionario))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeFuncionario)
                    .addComponent(jTextFieldNomeFuncionario))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRgFuncionario)
                    .addComponent(jTextFieldRgFuncionario))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCpfFuncionario)
                    .addComponent(jTextFieldCpfFuncionario))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDataNascFuncionario)
                    .addComponent(jTextFieldDataNascFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEndereçoFuncionario)
                    .addComponent(jTextFieldEnderecoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTelefoneFuncionario)
                    .addComponent(jTextFieldTelefoneFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFuncaoFuncionario)
                    .addComponent(jTextFieldFuncaoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSalarioFuncionario)
                    .addComponent(jTextFieldSalarioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCancelarFuncionario)
                            .addComponent(jButtonAlterarFuncionario))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCodigoFuncionario)
                        .addGap(42, 42, 42))))
        );

        jComboBoxCodigoCpf.getAccessibleContext().setAccessibleName("Código");

        jLabelAlterardeFuncionario.setText("Alterar de Funcionario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabelAlterardeFuncionario))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAlterardeFuncionario)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldFuncaoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFuncaoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFuncaoFuncionarioActionPerformed

    private void jButtonConsultarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarFuncionarioActionPerformed
        String opcaoConsulta = jComboBoxCodigoCpf.getSelectedItem().toString();
        if (opcaoConsulta.equals("Código")) {
            Funcionario funcionario = new Funcionario();
            FuncionarioDAO funcaoFuncionario = new FuncionarioDAO();
            try {
                funcionario = funcaoFuncionario.buscaFuncionarioCodigo(Integer.parseInt(jTextFieldCodigoCpfFuncionario.getText()));
                jTextFieldNomeFuncionario.setText(funcionario.getNome());
                jTextFieldRgFuncionario.setText(funcionario.getRG());
                jTextFieldCpfFuncionario.setText(funcionario.getCPF());
                jTextFieldDataNascFuncionario.setText(funcionario.getDataNasc());
                jTextFieldEnderecoFuncionario.setText(funcionario.getEndereco());
                jTextFieldTelefoneFuncionario.setText(funcionario.getTelefone());
                jTextFieldFuncaoFuncionario.setText(funcionario.getFuncao());
                jTextFieldSalarioFuncionario.setText(String.valueOf(funcionario.getSalario()));

            } catch (Exception e) {
                System.err.println(e.getMessage());
            }
        } else {
            Funcionario funcionario = new Funcionario();
            FuncionarioDAO funcaoFuncionario = new FuncionarioDAO();
            try {
                funcionario = funcaoFuncionario.buscaFuncionarioCpf(jTextFieldCodigoCpfFuncionario.getText());
                jTextFieldNomeFuncionario.setText(funcionario.getNome());
                jTextFieldRgFuncionario.setText(funcionario.getRG());
                jTextFieldCpfFuncionario.setText(funcionario.getCPF());
                jTextFieldDataNascFuncionario.setText(funcionario.getDataNasc());
                jTextFieldEnderecoFuncionario.setText(funcionario.getEndereco());
                jTextFieldTelefoneFuncionario.setText(funcionario.getTelefone());
                jTextFieldFuncaoFuncionario.setText(funcionario.getFuncao());
                jTextFieldSalarioFuncionario.setText(String.valueOf(funcionario.getSalario()));

            } catch (Exception e) {
                System.err.println(e.getMessage());
            }
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConsultarFuncionarioActionPerformed

    private void jComboBoxCodigoCpfItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCodigoCpfItemStateChanged
        // TODO add your handling code here:
        jTextFieldCodigoCpfFuncionario.setText("");
        jTextFieldNomeFuncionario.setText("");
        jTextFieldRgFuncionario.setText("");
        jTextFieldCpfFuncionario.setText("");
        jTextFieldDataNascFuncionario.setText("");
        jTextFieldEnderecoFuncionario.setText("");
        jTextFieldTelefoneFuncionario.setText("");
        jTextFieldFuncaoFuncionario.setText("");
        jTextFieldSalarioFuncionario.setText("");
    }//GEN-LAST:event_jComboBoxCodigoCpfItemStateChanged

    private void jButtonAlterarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarFuncionarioActionPerformed
        // TODO add your handling code here:
        
                int codigo = Integer.parseInt(jLabelCodigoFuncionario.getText());
        String nome = jTextFieldNomeFuncionario.getText();
        String rg = jTextFieldRgFuncionario.getText();
        String cpf = jTextFieldCpfFuncionario.getText();
        String dataNascTemp = jTextFieldDataNascFuncionario.getText();
        Util util = new Util();
        String dataNasc = util.inverteData(dataNascTemp);
        String endereco = jTextFieldEnderecoFuncionario.getText();
        String telefone = jTextFieldTelefoneFuncionario.getText();
        String funcao = jTextFieldFuncaoFuncionario.getText();
        double salario = Double.parseDouble(jTextFieldSalarioFuncionario.getText());
        

        Funcionario funcionario = new Funcionario(codigo, nome, endereco, telefone, rg, cpf, dataNasc, funcao, salario);
        FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
        try {
            funcionarioDAO.alteraFuncionario(funcionario);
            JOptionPane.showMessageDialog(null, "Funcionario atualizado com sucesso!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "SQL erro: " + e.getMessage());
        } finally {
            jTextFieldCodigoCpfFuncionario.setText("");
            jTextFieldNomeFuncionario.setText("");
            jTextFieldRgFuncionario.setText("");
            jTextFieldCpfFuncionario.setText("");
            jTextFieldDataNascFuncionario.setText("");
            jTextFieldEnderecoFuncionario.setText("");
            jTextFieldTelefoneFuncionario.setText("");
            jTextFieldFuncaoFuncionario.setText("");
            jTextFieldSalarioFuncionario.setText("");
            
        }

    }//GEN-LAST:event_jButtonAlterarFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlterarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarFuncionario;
    private javax.swing.JButton jButtonCancelarFuncionario;
    private javax.swing.JButton jButtonConsultarFuncionario;
    private javax.swing.JComboBox jComboBoxCodigoCpf;
    private javax.swing.JLabel jLabelAlterardeFuncionario;
    private javax.swing.JLabel jLabelCodigoFuncionario;
    private javax.swing.JLabel jLabelCpfFuncionario;
    private javax.swing.JLabel jLabelDataNascFuncionario;
    private javax.swing.JLabel jLabelEndereçoFuncionario;
    private javax.swing.JLabel jLabelFuncaoFuncionario;
    private javax.swing.JLabel jLabelNomeFuncionario;
    private javax.swing.JLabel jLabelRgFuncionario;
    private javax.swing.JLabel jLabelSalarioFuncionario;
    private javax.swing.JLabel jLabelTelefoneFuncionario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCodigoCpfFuncionario;
    private javax.swing.JTextField jTextFieldCpfFuncionario;
    private javax.swing.JTextField jTextFieldDataNascFuncionario;
    private javax.swing.JTextField jTextFieldEnderecoFuncionario;
    private javax.swing.JTextField jTextFieldFuncaoFuncionario;
    private javax.swing.JTextField jTextFieldNomeFuncionario;
    private javax.swing.JTextField jTextFieldRgFuncionario;
    private javax.swing.JTextField jTextFieldSalarioFuncionario;
    private javax.swing.JTextField jTextFieldTelefoneFuncionario;
    // End of variables declaration//GEN-END:variables
}
